-- use this file to map the AP location ids to your locations
-- first value is the code of the target location/item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
BASE_LOCATION_ID = 8350438193300
LOCATION_MAPPING = {
	[BASE_LOCATION_ID + 0x01] = { {"@Nature Orb/Nature Orb"} },
	[BASE_LOCATION_ID + 0x02] = { {"@Pack Up Forest Night/Pack Up"} },
	[BASE_LOCATION_ID + 0x03] = { {"@HP Up West Spectral/HP Up"} },
	[BASE_LOCATION_ID + 0x04] = { {"@Atk Up Forest Night/Atk Up"} },
	[BASE_LOCATION_ID + 0x05] = { {"@Pack Up Spectral/Pack Up"} },
	[BASE_LOCATION_ID + 0x06] = { {"@MP Up Cave/MP Up"} },
	[BASE_LOCATION_ID + 0x07] = { {"@HP Up Cave/HP Up"} },
	[BASE_LOCATION_ID + 0x08] = { {"@Toxic Strike/Toxic Strike"} },
	[BASE_LOCATION_ID + 0x09] = { {"@Piko Hammer/Piko Hammer"} },
	[BASE_LOCATION_ID + 0x0A] = { {"@MP Up Forest Cave/MP Up"} },
	[BASE_LOCATION_ID + 0x0B] = { {"@Tough Skin/Tough Skin"} },
	[BASE_LOCATION_ID + 0x0C] = { {"@Regen Up Cave/Regen Up"} },
	[BASE_LOCATION_ID + 0x0D] = { {"@HP Up North Forest/HP Up"} },
	[BASE_LOCATION_ID + 0x0E] = { {"@Wall Jump/Wall Jump"} },
	[BASE_LOCATION_ID + 0x0F] = { {"@Regen Up Mid Forest/Regen Up"} },
	[BASE_LOCATION_ID + 0x10] = { {"@MP Up Mid Spectral/MP Up"} },
	[BASE_LOCATION_ID + 0x11] = { {"@HP Up Mid Spectral/HP Up"} },
	[BASE_LOCATION_ID + 0x12] = { {"@Carrot Bomb/Carrot Bomb"} },
	[BASE_LOCATION_ID + 0x13] = { {"@Def Trade/Def Trade"} },
	[BASE_LOCATION_ID + 0x14] = { {"@Light Orb/Light Orb"} },
	[BASE_LOCATION_ID + 0x15] = { {"@HP Up Forest Post Cocoa/HP Up"} },
	[BASE_LOCATION_ID + 0x16] = { {"@Charge Ring/Charge Ring"} },
	[BASE_LOCATION_ID + 0x17] = { {"@Arm Strength/Arm Strength"} },
	[BASE_LOCATION_ID + 0x18] = { {"@Regen Up East Forest/Regen Up"} },
	[BASE_LOCATION_ID + 0x19] = { {"@Mana Wager/Mana Wager"} },
	[BASE_LOCATION_ID + 0x1A] = { {"@MP Up East Forest/MP Up"} },
	[BASE_LOCATION_ID + 0x1B] = { {"@Pack Up East Forest/Pack Up"} },
	[BASE_LOCATION_ID + 0x1C] = { {"@MP Up Cicini/MP Up"} },
	[BASE_LOCATION_ID + 0x1D] = { {"@MP Up Northeast Forest/MP Up"} },

	[BASE_LOCATION_ID + 0x1E] = { {"@Survival/Survival"} },
	[BASE_LOCATION_ID + 0x1F] = { {"@Health Wager/Health Wager"} },
	[BASE_LOCATION_ID + 0x20] = { {"@Atk Up Beach Cave/Atk Up"} },
	[BASE_LOCATION_ID + 0x21] = { {"@MP Up Graveyard Warp/MP Up"} },
	[BASE_LOCATION_ID + 0x22] = { {"@HP Up Graveyard/HP Up"} },
	[BASE_LOCATION_ID + 0x23] = { {"@Sunny Beam/Sunny Beam"} },
	[BASE_LOCATION_ID + 0x24] = { {"@MP Up Upper Graveyard/MP Up"} },
	[BASE_LOCATION_ID + 0x25] = { {"@Auto Earrings/Auto Earrings"} },
	[BASE_LOCATION_ID + 0x26] = { {"@Health Plus/Health Plus"} },
	[BASE_LOCATION_ID + 0x27] = { {"@MP Up Pyramid Dark Room/MP Up"} },
	[BASE_LOCATION_ID + 0x28] = { {"@Crisis Boost/Crisis Boost"} },
	[BASE_LOCATION_ID + 0x29] = { {"@Atk Up Graveyard/Atk Up"} },
	[BASE_LOCATION_ID + 0x2A] = { {"@HP Up Inner Pyramid/HP Up"} },
	[BASE_LOCATION_ID + 0x2B] = { {"@HP Up Beach/HP Up"} },
	[BASE_LOCATION_ID + 0x2C] = { {"@Atk Up Pyramid/Atk Up"} },
	[BASE_LOCATION_ID + 0x2D] = { {"@Pack Up Pyramid/Pack Up"} },
	[BASE_LOCATION_ID + 0x2E] = { {"@Armored/Armored"} },
	[BASE_LOCATION_ID + 0x2F] = { {"@Chaos Rod/Chaos Rod"} },
	[BASE_LOCATION_ID + 0x30] = { {"@Pack Up Beach/Pack Up"} },
	[BASE_LOCATION_ID + 0x31] = { {"@Top Form/Top Form"} },
	[BASE_LOCATION_ID + 0x32] = { {"@HP Up Pyramid Entrance/HP Up"} },
	[BASE_LOCATION_ID + 0x33] = { {"@MP Up Pyramid Bomb Block Room/MP Up"} },
	[BASE_LOCATION_ID + 0x34] = { {"@Air Dash/Air Dash"} },
	[BASE_LOCATION_ID + 0x35] = { {"@Regen Up Pyramid/Regen Up"} },
	[BASE_LOCATION_ID + 0x36] = { {"@Pure Love/Pure Love"} },
	[BASE_LOCATION_ID + 0x37] = { {"@MP Up Beach Tunnel/MP Up"} },
	[BASE_LOCATION_ID + 0x38] = { {"@Hourglass/Hourglass"} },
	[BASE_LOCATION_ID + 0x39] = { {"@HP Up Sky Island/HP Up"} },
	[BASE_LOCATION_ID + 0x3A] = { {"@Pack Up Sky Island/Pack Up"} },
	[BASE_LOCATION_ID + 0x3B] = { {"@Regen Up Sky Island/Regen Up"} },
	[BASE_LOCATION_ID + 0x3C] = { {"@MP Up Beach Pillar/MP Up"} },

	[BASE_LOCATION_ID + 0x3D] = { {"@Def Grow/Def Grow"} },
	[BASE_LOCATION_ID + 0x3E] = { {"@Atk Up Park/Atk Up"} },
	[BASE_LOCATION_ID + 0x3F] = { {"@Atk Trade/Atk Trade"} },
	[BASE_LOCATION_ID + 0x40] = { {"@HP Up Park/HP Up"} },
	[BASE_LOCATION_ID + 0x41] = { {"@Rabi Slippers/Rabi Slippers"} },
	[BASE_LOCATION_ID + 0x42] = { {"@Regen Up Park/Regen Up"} },
	[BASE_LOCATION_ID + 0x43] = { {"@Health Surge/Health Surge"} },
	[BASE_LOCATION_ID + 0x44] = { {"@MP Up Sky Bridge/MP Up"} },
	[BASE_LOCATION_ID + 0x45] = { {"@MP Up UPRPRC HQ/MP Up"} },
	[BASE_LOCATION_ID + 0x46] = { {"@MP Up Park/MP Up"} },
	[BASE_LOCATION_ID + 0x47] = { {"@Hex Cancel/Hex Cancel"} },
	[BASE_LOCATION_ID + 0x48] = { {"@HP Up Sky Bridge/HP Up"} },
	[BASE_LOCATION_ID + 0x49] = { {"@Pack Up Sky Bridge/Pack Up"} },
	[BASE_LOCATION_ID + 0x4A] = { {"@Regen Up Sky Bridge/Regen Up"} },
	[BASE_LOCATION_ID + 0x4B] = { {"@Lucky Seven/Lucky Seven"} },
	[BASE_LOCATION_ID + 0x4C] = { {"@Atk Up Vanilla/Atk Up"} },
	[BASE_LOCATION_ID + 0x4D] = { {"@Hammer Wave/Hammer Wave"} },
	[BASE_LOCATION_ID + 0x4E] = { {"@Atk Up West Ravine/Atk Up"} },
	[BASE_LOCATION_ID + 0x4F] = { {"@HP Up South Ravine/HP Up"} },
	[BASE_LOCATION_ID + 0x50] = { {"@Atk Up North Ravine/Atk Up"} },
	[BASE_LOCATION_ID + 0x51] = { {"@HP Up Mid Ravine/HP Up"} },
	[BASE_LOCATION_ID + 0x52] = { {"@MP Up Ravine/MP Up"} },
	[BASE_LOCATION_ID + 0x53] = { {"@Regen Up Ravine/Regen Up"} },
	[BASE_LOCATION_ID + 0x54] = { {"@Mana Surge/Mana Surge"} },

	[BASE_LOCATION_ID + 0x55] = { {"@HP Up Palace/HP Up"} },
	[BASE_LOCATION_ID + 0x56] = { {"@Water Orb/Water Orb"} },
	[BASE_LOCATION_ID + 0x57] = { {"@HP Up West Aquarium/HP Up"} },
	[BASE_LOCATION_ID + 0x58] = { {"@Mana Plus/Mana Plus"} },
	[BASE_LOCATION_ID + 0x59] = { {"@Atk Up Palace/Atk Up"} },
	[BASE_LOCATION_ID + 0x5A] = { {"@Atk Up Snowland/Atk Up"} },
	[BASE_LOCATION_ID + 0x5B] = { {"@Regen Up Palace/Regen Up"} },
	[BASE_LOCATION_ID + 0x5C] = { {"@Stamina Plus/Stamina Plus"} },
	[BASE_LOCATION_ID + 0x5D] = { {"@MP Up Palace/MP Up"} },
	[BASE_LOCATION_ID + 0x5E] = { {"@Self Defense/Self Defense"} },
	[BASE_LOCATION_ID + 0x5F] = { {"@HP Up Upper Aquarium/HP Up"} },
	[BASE_LOCATION_ID + 0x60] = { {"@Gold Carrot/Gold Carrot"} },
	[BASE_LOCATION_ID + 0x61] = { {"@Atk Up Upper Aquarium/Atk Up"} },
	[BASE_LOCATION_ID + 0x62] = { {"@Pack Up Icy Summit/Pack Up"} },
	[BASE_LOCATION_ID + 0x63] = { {"@Atk Up Icy Summit/Atk Up"} },
	[BASE_LOCATION_ID + 0x64] = { {"@Atk Up Mid Aquarium/Atk Up"} },
	[BASE_LOCATION_ID + 0x65] = { {"@MP Up Icy Summit/MP Up"} },
	[BASE_LOCATION_ID + 0x66] = { {"@MP Up Snowland/MP Up"} },
	[BASE_LOCATION_ID + 0x67] = { {"@Quick Barrette/Quick Barrette"} },
	[BASE_LOCATION_ID + 0x68] = { {"@HP Up Icy Summit/HP Up"} },
	[BASE_LOCATION_ID + 0x69] = { {"@Super Carrot/Super Carrot"} },
	[BASE_LOCATION_ID + 0x6A] = { {"@Regen Up Snowland Water/Regen Up"} },
	[BASE_LOCATION_ID + 0x6B] = { {"@MP Up Aquarium/MP Up"} },
	[BASE_LOCATION_ID + 0x6C] = { {"@HP Up Snowland/HP Up"} },
	[BASE_LOCATION_ID + 0x6D] = { {"@Carrot Boost/Carrot Boost"} },
	[BASE_LOCATION_ID + 0x6E] = { {"@Regen Up Aquarium/Regen Up"} },
	[BASE_LOCATION_ID + 0x6F] = { {"@Pack Up Aquarium/Pack Up"} },

	[BASE_LOCATION_ID + 0x70] = { {"@Regen Up Northwest Riverbank/Regen Up"} },
	[BASE_LOCATION_ID + 0x71] = { {"@Pack Up Riverbank/Pack Up"} },
	[BASE_LOCATION_ID + 0x72] = { {"@MP Up Southwest Riverbank/MP Up"} },
	[BASE_LOCATION_ID + 0x73] = { {"@Atk Grow/Atk Grow"} },
	[BASE_LOCATION_ID + 0x74] = { {"@Regen Up South Riverbank/Regen Up"} },
	[BASE_LOCATION_ID + 0x75] = { {"@Atk Up Riverbank Pit/Atk Up"} },
	[BASE_LOCATION_ID + 0x76] = { {"@Bunny Whirl/Bunny Whirl"} },
	[BASE_LOCATION_ID + 0x77] = { {"@Explode Shot/Explode Shot"} },
	[BASE_LOCATION_ID + 0x78] = { {"@MP Up Mid Riverbank/MP Up"} },
	[BASE_LOCATION_ID + 0x79] = { {"@Atk Up East Riverbank/Atk Up"} },
	[BASE_LOCATION_ID + 0x7A] = { {"@Spike Barrier/Spike Barrier"} },
	[BASE_LOCATION_ID + 0x7B] = { {"@Frame Cancel/Frame Cancel"} },
	[BASE_LOCATION_ID + 0x7C] = { {"@HP Up Lab Slide Tunnel/HP Up"} },
	[BASE_LOCATION_ID + 0x7D] = { {"@MP Up Lab/MP Up"} },
	[BASE_LOCATION_ID + 0x7E] = { {"@HP Up Riverbank/HP Up"} },
	[BASE_LOCATION_ID + 0x7F] = { {"@MP Up Evernight/MP Up"} },
	[BASE_LOCATION_ID + 0x80] = { {"@HP Up Evernight/HP Up"} },
	[BASE_LOCATION_ID + 0x81] = { {"@HP Up Lab Pit/HP Up"} },
	[BASE_LOCATION_ID + 0x82] = { {"@Sliding Powder/Sliding Powder"} },
	[BASE_LOCATION_ID + 0x83] = { {"@Atk Up Evernight UPRPRC/Atk Up"} },
	[BASE_LOCATION_ID + 0x84] = { {"@Cashback/Cashback"} },
	[BASE_LOCATION_ID + 0x85] = { {"@Plus Necklace/Plus Necklace"} },
	[BASE_LOCATION_ID + 0x86] = { {"@Weaken/Weaken"} },
	[BASE_LOCATION_ID + 0x87] = { {"@Atk Up Lab Computer/Atk Up"} },
	[BASE_LOCATION_ID + 0x88] = { {"@Pack Up South Evernight/Pack Up"} },
	[BASE_LOCATION_ID + 0x89] = { {"@Pack Up North Evernight/Pack Up"} },
	[BASE_LOCATION_ID + 0x8A] = { {"@Regen Up Evernight/Regen Up"} },
	[BASE_LOCATION_ID + 0x8B] = { {"@Atk Up Evernight/Atk Up"} },
	[BASE_LOCATION_ID + 0x8C] = { {"@Atk Up East Lab/Atk Up"} },
	[BASE_LOCATION_ID + 0x8D] = { {"@Pack Up Lab/Pack Up"} },
	[BASE_LOCATION_ID + 0x8E] = { {"@Hammer Roll/Hammer Roll"} },

	[BASE_LOCATION_ID + 0x8F] = { {"@HP Up Volcanic/HP Up"} },
	[BASE_LOCATION_ID + 0x90] = { {"@Fire Orb/Fire Orb"} },
	[BASE_LOCATION_ID + 0x91] = { {"@Pack Up Volcanic/Pack Up"} },

	[BASE_LOCATION_ID + 0x92] = { {"@Regen Up Cyberspace/Regen Up"} },
	[BASE_LOCATION_ID + 0x93] = { {"@Pack Up Cyberspace/Pack Up"} },
	[BASE_LOCATION_ID + 0x94] = { {"@Air Jump/Air Jump"} },
	[BASE_LOCATION_ID + 0x95] = { {"@HP Up Cyberspace/HP Up"} },
	[BASE_LOCATION_ID + 0x96] = { {"@Atk Up Cyberspace/Atk Up"} },
	[BASE_LOCATION_ID + 0x97] = { {"@MP Up Cyberspace/MP Up"} },

	[BASE_LOCATION_ID + 0x98] = { {"@P Hairpin/P Hairpin"} },
	[BASE_LOCATION_ID + 0x99] = { {"@Town Gift Items/Speed Boost"} },
	[BASE_LOCATION_ID + 0x9A] = { {"@Town Gift Items/Bunny Strike"} },

	[BASE_LOCATION_ID + 0x9B] = { {"@Egg Forest Night Aruraune/Egg"} },
	[BASE_LOCATION_ID + 0x9C] = { {"@Egg Spectral West/Egg"} },
	[BASE_LOCATION_ID + 0x9D] = { {"@Egg Cave Under Hammer/Egg"} },
	[BASE_LOCATION_ID + 0x9E] = { {"@Egg Forest Night East/Egg"} },
	[BASE_LOCATION_ID + 0x9F] = { {"@Egg Spectral Slide/Egg"} },
	[BASE_LOCATION_ID + 0xA0] = { {"@Egg Cave Cocoa/Egg"} },
	[BASE_LOCATION_ID + 0xA1] = { {"@Egg Forest Northeast Ledge/Egg"} },
	[BASE_LOCATION_ID + 0xA2] = { {"@Egg Forest Northeast Pedestal/Egg"} },

	[BASE_LOCATION_ID + 0xA3] = { {"@Egg Beach to Aquarium/Egg"} },
	[BASE_LOCATION_ID + 0xA4] = { {"@Egg Graveyard Near Library/Egg"} },
	[BASE_LOCATION_ID + 0xA5] = { {"@Egg Pyramid Beach/Egg"} },
	[BASE_LOCATION_ID + 0xA6] = { {"@Egg Pyramid Lower/Egg"} },
	[BASE_LOCATION_ID + 0xA7] = { {"@Egg Sky Town/Egg"} },
	
	[BASE_LOCATION_ID + 0xA8] = { {"@Egg Park Spikes/Egg"} },
	[BASE_LOCATION_ID + 0xA9] = { {"@Egg Park Green Kotri/Egg"} },
	[BASE_LOCATION_ID + 0xAA] = { {"@Egg UPRPRC Base/Egg"} },
	[BASE_LOCATION_ID + 0xAB] = { {"@Egg Sky Bridge Warp/Egg"} },
	[BASE_LOCATION_ID + 0xAC] = { {"@Egg Sky Bridge by Vanilla/Egg"} },
	[BASE_LOCATION_ID + 0xAD] = { {"@Egg Ravine Above Chocolate/Egg"} },
	[BASE_LOCATION_ID + 0xAE] = { {"@Egg Ravine Mid/Egg"} },

	[BASE_LOCATION_ID + 0xAF] = { {"@Egg Snowland to Evernight/Egg"} },
	[BASE_LOCATION_ID + 0xB0] = { {"@Egg Palace Bridge/Egg"} },
	[BASE_LOCATION_ID + 0xB1] = { {"@Egg Aquarium/Egg"} },
	[BASE_LOCATION_ID + 0xB2] = { {"@Egg Palace Wall/Egg"} },
	[BASE_LOCATION_ID + 0xB3] = { {"@Egg Snowland Warp/Egg"} },
	[BASE_LOCATION_ID + 0xB4] = { {"@Egg Icy Summit Nixie/Egg"} },
	[BASE_LOCATION_ID + 0xB5] = { {"@Egg Icy Summit Warp/Egg"} },
	[BASE_LOCATION_ID + 0xB6] = { {"@Egg Snowland Lake/Egg"} },

	[BASE_LOCATION_ID + 0xB7] = { {"@Egg Riverbank Spider Spike/Egg"} },
	[BASE_LOCATION_ID + 0xB8] = { {"@Egg Riverbank Wall/Egg"} },
	[BASE_LOCATION_ID + 0xB9] = { {"@Egg Lab/Egg"} },
	[BASE_LOCATION_ID + 0xBA] = { {"@Egg Evernight Mid/Egg"} },
	[BASE_LOCATION_ID + 0xBB] = { {"@Egg Evernight Saya/Egg"} },

	[BASE_LOCATION_ID + 0xBC] = { {"@Egg Town/Egg"} },

	[BASE_LOCATION_ID + 0xBD] = { {"@Egg Plurk Cats/Egg"} },
	[BASE_LOCATION_ID + 0xBE] = { {"@Egg Plurk Cave/Egg"} },
	[BASE_LOCATION_ID + 0xBF] = { {"@Egg Plurk East/Egg"} },

	[BASE_LOCATION_ID + 0xC0] = { {"@Egg Volcanic Bomb Bunnies/Egg"} },
	[BASE_LOCATION_ID + 0xC1] = { {"@Egg Volcanic Fire Orb/Egg"} },
	[BASE_LOCATION_ID + 0xC2] = { {"@Egg Volcanic Northeast/Egg"} },
	[BASE_LOCATION_ID + 0xC3] = { {"@Egg Volcanic Big Drop/Egg"} },

	[BASE_LOCATION_ID + 0xC5] = { {"@Egg System Interior/Egg"} },
}
